kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: newrelic-operator-test
subjects:
- kind: ServiceAccount
  name: newrelic-operator-test
  namespace:  default
roleRef:
  kind: ClusterRole
  name: newrelic-operator-test
  apiGroup: rbac.authorization.k8s.io
