kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: newrelic-operator-test
rules:
- apiGroups:
  - newrelic.shanestarcher.com
  resources:
  - '*'
  - alertchannels
  - alertpolicies
  - dashboards
  - monitors
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
